### ISSUE TITLE
node global installation process failure

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/roslibjs#131]
follow up from #127 

```
jihoonl@whoola:~$ sudo npm install -g roslib
[sudo] password for jihoonl: 
-
> roslib@0.9.0 preinstall /usr/local/lib/node_modules/roslib
> sh misc/install.sh

[sudo] password for nobody: 
Sorry, try again.
[sudo] password for nobody: 
Sorry, try again.
[sudo] password for nobody: 
Sorry, try again.
sudo: 3 incorrect password attempts
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
```

npm version 0.9.0 Testing.

**local installation**

> npm install roslib

 works fine.

**global installation**

> sudo npm install -g roslib

It seems like preinstall process causing problems.

* asking sudo for nobody
* node-canvas installation using curl command.

**Comment by T045T** [comment]
This should be fixed with #178, since the installation no longer requires ```sudo```
