### ISSUE TITLE
New TF implementation not working

### ISSUE THREAD

**Issue by rctoris** [RobotWebTools/roslibjs#152]
@T045T I released the new version of roslibjs with the new TF implementation and TFs are no longer working correctly. Looks like no TFs are handled correctly (see screenshot). 

![untitled](https://cloud.githubusercontent.com/assets/954667/6044431/3c378ebe-ac61-11e4-88f2-8181664dec81.png)

Since this is a critical bug I'm going to revert and re-release!

**Comment by T045T** [comment]
Can you give a minimal (non-)working example? I've tested the new TF implementation a number of times and never run into this.

**Comment by rctoris** [comment]
The example above is from the RWT demo https://github.com/RobotWebTools/robotwebtools.github.io/blob/master/demos/carl-urdf.html 

It's running on Indigo with:

`sudo apt-get install ros-indigo-carl-description`

```
<launch> 
  <include file="$(find rosbridge_server)/launch/rosbridge_websocket.launch" />
  <node pkg="tf2_web_republisher" type="tf2_web_republisher" name="tf2_web_republisher" />
  <include file="$(find carl_description)/launch/carl_description.launch" />
</launch>
```
