### ISSUE TITLE
release 0.13.0 in npm

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/roslibjs#169]
to sync with browser version.

**Comment by jihoonl** [comment]
https://github.com/RobotWebTools/roslibjs/releases/tag/node-0.13.0

**Comment by rctoris** [comment]
How are the node tags different than the regular tags?
https://github.com/RobotWebTools/roslibjs/tags

**Comment by megawac** [comment]
Should just add a script to tag on node and git. There's a couple grunt options I'm aware. Tagging node-x.x doesn't seem necessary

**Comment by jihoonl** [comment]
No differences. Just to make sure it is released in npm. Would it be better to have `0.13.0`?
