### ISSUE TITLE
Remove sudo from npm install

### ISSUE THREAD

**Issue by rctoris** [RobotWebTools/roslibjs#177]
Currently `npm install` will run `misc/install.sh` which runs some sudo commands. This is unexpected behavior to many and breaks many automated scripts. I propose removing this from the npm install script and placing the instruction to run the script in the README instead.

**Comment by megawac** [comment]
Related #133. Ideally we could detect if `libcario` is installed. If it isn't

a) install it (requiring sudo)
b) Error the build and give users instruction on how to install it

**Comment by jihoonl** [comment]
I would suggest b) to resolve the issue.  This is issue of `node-canvas` not internal problem of `roslibjs`.

**Comment by rctoris** [comment]
+1 to `b`

**Comment by rctoris** [comment]
@jihoonl can you run a npm release to propagate this please?

**Comment by jihoonl** [comment]
Done.

https://www.npmjs.com/package/roslib
