### ISSUE TITLE
New Release of roslibjs with BSON Encoding

### ISSUE THREAD

**Issue by DLu** [RobotWebTools/roslibjs#188]
Also, it would be great to add a version of [bson.js](https://github.com/mongodb/js-bson/blob/master/browser_build/bson.js) to the CDN.

**Comment by rctoris** [comment]
http://cdn.robotwebtools.org/roslibjs/current/roslib.js
http://cdn.robotwebtools.org/roslibjs/current/roslib.min.js

http://cdn.robotwebtools.org/js-bson/current/bson.js
http://cdn.robotwebtools.org/js-bson/current/bson.min.js
