### ISSUE TITLE
Require messing up doc generation

### ISSUE THREAD

**Issue by rctoris** [RobotWebTools/roslibjs#206]
Looks like the require statements are being picked up incorrectly for jsdoc. See https://github.com/RobotWebTools/robotwebtools.github.io/issues/53 and https://github.com/RobotWebTools/robotwebtools.github.io/issues/52

**Comment by Rayman** [comment]
I think this was fixed by #195, but it hasn't been deployed yet.

**Comment by rctoris** [comment]
Oh okay, I'll add a re-deploy of the docks to my stack. Thanks!!

**Comment by rctoris** [comment]
Regen in https://github.com/RobotWebTools/robotwebtools.github.io/commit/f12cd54ebf7e0f74a31efb78b887faa3dbe96801
