### ISSUE TITLE
releasing 0.18?

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/roslibjs#209]
@rctoris  :)

**Comment by rctoris** [comment]
Will do shortly! :+1:

**Comment by rctoris** [comment]
https://github.com/RobotWebTools/roslibjs/pull/210

**Comment by rctoris** [comment]
CDN is clearing cache now should be good in 5-minutes

**Comment by jihoonl** [comment]
Done in npm as well.

https://www.npmjs.com/package/roslib
