### ISSUE TITLE
SPDX license expression

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/roslibjs#211]
`npm update` complaints...

```
npm WARN roslib@0.19.0-SNAPSHOT license should be a valid SPDX license expression
```

Does anybody know what it is?

**Comment by rctoris** [comment]
Maybe the license has to be in one of these forms? https://spdx.org/licenses/

**Comment by rctoris** [comment]
https://github.com/RobotWebTools/roslibjs/blob/develop/package.json#L6

**Comment by vkuehn** [comment]
Hi, was looking for simple bugs....is that really still an issue ? could you close solved problems ?

**Comment by jihoonl** [comment]
Should be ok to close. closing
