### ISSUE TITLE
groovyCompatibility option in core/Ros.js

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/roslibjs#212]
`groovyCompatiblity` Option is on and off by @T045T and @rctoris.
Should this option be in or out?

[core/Ros.js](https://github.com/RobotWebTools/roslibjs/blob/develop/src/core/Ros.js) history
* Dec 11 2014. [add groovyCompatibility option to Ros] (https://github.com/RobotWebTools/roslibjs/commit/de19b90f039037da356eb9e99f8dcc5a57b8cff6) @T045T 
* Feb 5 2015. [0.12.0](https://github.com/RobotWebTools/roslibjs/commit/a5cfa51c6df727a5b90048ceb867d77ea27c61a3) @rctoris 
 * groovyCompatibility option removed.
* Mar 18 2015. [put groovyCompatibility option back in](https://github.com/RobotWebTools/roslibjs/commit/bbfcea0c8d8eaa465b24512ad11bd927f9ca8279) @T045T

**Comment by rctoris** [comment]
It was taken out on Feb 2015 since it didn't work and was causing major bugs in the release version. It was then fixed and added back in Mar 2015 and works properly.
