### ISSUE TITLE
Deprecated CanvasRendering Message

### ISSUE THREAD

**Issue by DLu** [RobotWebTools/roslibjs#216]
In src/util/shim/decompressPng.js: 
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

**Comment by T045T** [comment]
from https://github.com/RobotWebTools/roslibjs/blob/develop/src/util/shim/decompressPng.js#L35-L37 :
```javascript
    context.imageSmoothingEnabled = false;
    context.webkitImageSmoothingEnabled = false;
    context.mozImageSmoothingEnabled = false;
```

The new method is used along with the browser-specific old ones - I think it's a good idea to leave those in case people are using an older browser for whatever reason. We should probably even add `msImageSmoothingEnabled` for IE.

**Comment by DLu** [comment]
That's fair.
