### ISSUE TITLE
Connecting on secure websocket

### ISSUE THREAD

**Issue by namgk** [RobotWebTools/roslibjs#228]
Hi there,

I'm using roslibjs with NodeJS.

I found that it's not currently support wss. It seems you have to change only one line in https://github.com/RobotWebTools/roslibjs/blob/master/src/node/RosTCP.js#L36

to something like:

`if (typeof url === 'string' && (url.slice(0, 5) === 'ws://' || url.slice(0, 6) === 'wss://')) {
`
Can anyone confirm?

**Comment by aqiank** [comment]
Just got into that issue today. Your solution worked!

**Comment by jihoonl** [comment]
fixed.
