### ISSUE TITLE
Wrong video link for speech_commands libray

### ISSUE THREAD

**Issue by alecive** [RobotWebTools/roslibjs#230]
Hi,

this is a very minor issue, but I thought it was worth posting. In http://robotwebtools.org/tools.html , the `video` link for the `speech_commands` library points to a 404 error. The only thing you should change is to remove the `.` from the link itself.

Thank you!

**Comment by janga1997** [comment]
The issue has been fixed. See [here](https://github.com/RobotWebTools/robotwebtools.github.io/pull/56).

**Comment by alecive** [comment]
Thanks!
