### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by marcoarruda** [RobotWebTools/roslibjs#232]
Is there someone working to create a declaration file to enable integration with TypeScript?
I'd like to start it, if not.
Is it relevant?

Thanks!

**Comment by smamessier** [comment]
Check that, it seems pretty complete.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/roslib

**Comment by marcoarruda** [comment]
Nice, i didn't notice the message "Sorry, we had to truncate this directory to 1,000 files. 966 entries were omitted from the list."
Thanks!

**Comment by rabbishuki** [comment]
@smamessier seems like you have a typo in the link.

The correct link is:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/roslib
