### ISSUE TITLE
Using this with npm and React

### ISSUE THREAD

**Issue by cjds** [RobotWebTools/roslibjs#252]
I installed the library via npm, and was trying to include it in my application like so:

    import ROSLIB from 'roslib';

However, this fails with this error:

>Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.187../ServiceRequest (Service.js:28)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.186../Service (Ros.js:9)

which corresponds to this in the source:

    Service.prototype.__proto__ = EventEmitter2.prototype;

**Comment by valerybugakov** [comment]
@cjds I've found a workaround for this issue. Add this snippet at the beginning of your JS entry file:
```js
import EventEmitter2 from 'eventemitter2'

window.EventEmitter2 = EventEmitter2.EventEmitter2
```

**Comment by cjds** [comment]
@valerybugakov  That didn't fix it.

Doing some further investigation:

When I'm loading this through my require I get this output for `console.log(EventEmitter2)`:

    Object {EventEmitter2: undefined}

However, when I call it independently (add a require completely out of this library), I get this object:

```
function EventEmitter(conf) {
    this._events = {};
    this.newListener = false;
    this.verboseMemoryLeak = false;
    configure.call(this, conf);
}
```

**Comment by valerybugakov** [comment]
@cjds Hmm, I've fixed the same error you described above using this snippet. Also I did `yarn install eventemitter2` before that. Hope it will help!

**Comment by subvertallchris** [comment]
I do this:

```
window.EventEmitter2 = require('eventemitter2');
window.ROSLIB = require('roslib/src/RosLib');
```

And when I reference ROSLIB in my code, I'm forced to rely on `window.ROSLIB`. It feels a little gross but it works.

**Comment by ludusrusso** [comment]
I'm having a similar issues with angular2 + roslibjs!
But I'm not able to find a workaround!

**Comment by BogdanAlexandru** [comment]
I ran into an identical issue when trying to use roslibj in a project using requirejs. In the end I chose to have a separate project whose sole purpose was to let the original project communicate with roslibjs, as I was pressed for time.

**Comment by ludusrusso** [comment]
After some search, I found out https://github.com/RobotWebTools/roslibjs/pull/221, that solves a similar dependency issue! It's been integrated in the develop branch. I solved by installing this branch using
`npm install git://github.com/RobotWebTools/roslibjs#develop --save`

**Comment by paulashbourne** [comment]
Hi all, does anyone know if this fill will be making its way into a future release?

**Comment by jihoonl** [comment]
latest version 0.20.0 is released in Jan 3rd 2018. It should have this change.

**Comment by bel7aG** [comment]
**SOLUTION:**

Make sure you import ROSLIB like this:

`import * as ROSLIB from 'roslib'`
