### ISSUE TITLE
Creating a New Message Type.

### ISSUE THREAD

**Issue by sradmard** [RobotWebTools/roslibjs#254]
Hi,

I was wondering how I can create a new message type that can be recognised by roslibjs. I need to create a new message type and be able to access to that through roslib. 

Thank you so much in advance for any help.

**Comment by marcoarruda** [comment]
I think I had a problem like this before.
After creating a new message and compiled it inside a robot, my rosbridge server wasn't able to recognize this new message, when trying subscribe a topic.

If you are working with more than 1 computer (like I was), you must compile/generate this new message in the publisher side (e.g: your robot) and also in the rosbridge server computer (e.g: ground station), which is subscribing to it.

**Comment by jihoonl** [comment]
@marcoarruda's answer is correct. The PC which runs rosbridge_server should have the newly created message type. `roslibjs` is just a client that receives JSON data that is formatted by rosbridge server.
