### ISSUE TITLE
bower installation failure

### ISSUE THREAD

**Issue by DWatkins** [RobotWebTools/roslibjs#266]
roslibjs as installed by bower

```
bower install roslibjs
```

fails because the `eventemitter2` dependency cannot be resolved properly.

I tried manually installing event emitter in both bower and npm and nothing worked.

**Comment by jihoonl** [comment]
Hello, we were just discussing how we should support bower in #265. I saw that [official bower recommends moving away](https://bower.io/blog/2017/how-to-migrate-away-from-bower/). Would npm be option for you?

**Comment by DWatkins** [comment]
npm would definitely be ideal.

**Comment by jihoonl** [comment]
Yup then I suggest to use npm to get roslib instead of bower
