### ISSUE TITLE
wrong name in bower.json?

### ISSUE THREAD

**Issue by ensonic** [RobotWebTools/roslibjs#269]
See
https://github.com/RobotWebTools/roslibjs/blob/develop/bower.json#L2

should this be `roslibjs` instead of `roslib`? I can send a PR.

**Comment by jihoonl** [comment]
No, it should be `roslib` to match with the module name. And, it has been serving the module as `roslib` quite a while already. So, it would make sense to stay with the current naming.

**Comment by jihoonl** [comment]
It is also [roslib in package.json](https://github.com/RobotWebTools/roslibjs/blob/develop/package.json)

**Comment by ensonic** [comment]
Ok, but then packages like
https://github.com/RobotWebTools/ros3djs/blob/develop/bower.json#L26
should probably reference it as "roslib", right?
