### ISSUE TITLE
Topic Types does not match : [Sensor_msgs/Image] vs [sensor_msgs/CompressedImage]

### ISSUE THREAD

**Issue by pushkalkatara** [RobotWebTools/roslibjs#272]
Referred this tutorial  -
http://wiki.ros.org/roslibjs/Tutorials/Publishing%20video%20and%20IMU%20data%20with%20roslibjs
topics type not match error. 
http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/CompressedImage.html
http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/Image.html

Is this tutorial synced with updates?

**Comment by pushkalkatara** [comment]
Does CompressedImage take only JPEG as input?

**Comment by jihoonl** [comment]
This tutorial seems to have been created by someone in the community. But, I think it should work anyway. What do you mean by topics type not match error?

> Does CompressedImage take only JPEG as input?

[sensor_msgs/CompressedImage](http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/CompressedImage.html) can accept either jpeg or png. See the format description

**Comment by pushkalkatara** [comment]
![a](https://user-images.githubusercontent.com/21266230/32621381-a555462e-c5a5-11e7-975a-167ffb4efa29.png)
![b](https://user-images.githubusercontent.com/21266230/32621382-a58e5d1a-c5a5-11e7-9449-7c2c92611b85.png)

**Comment by pushkalkatara** [comment]
Solved this issue recently, imageview was not able to display the image but a simple opencv workaround worked.
```python        np_arr = np.fromstring(ros_data.data, np.uint8)
        image_np = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
        cv2.imshow('cv_img', image_np)
        cv2.waitKey(2)
```

Though the video is lagging and saturating the rosbridge. Please suggest alternatives.

**Comment by cyberphantom** [comment]
Any solution to this problem yet?
 @pushkalkatara I tried your suggested imdecode in the callback function to subscribe to the compressed Image but I'm getting an  error

`    self.frame = cv2.imdecode(np.frombuffer(data, cv2.IMREAD_COLOR), 1)
TypeError: data type not understood
`

**Comment by T045T** [comment]
Are you sure the bridge is saturated?
The example you linked only sends camera frames (at 640 pixels width) every 250ms. That shouldn't be enough to cause lag, but it *is* just 4fps, which might be why it seems laggy.
