### ISSUE TITLE
robotwebtools cdn is broken (gone?)

### ISSUE THREAD

**Issue by minshallj** [RobotWebTools/roslibjs#274]
It looks like http://cdn.robotwebtools.org/EventEmitter2/current/eventemitter2.min.js and http://cdn.robotwebtools.org/roslibjs/current/roslib.min.js (and all of cdn.robotwebtools.org) no longer work. It would be nice to get an official CDN set up again. This would hopefully include changing the roslibjs tutorial at http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality

**Comment by keego** [comment]
Just ran into this issue today when attempting the [Simple Interactive Markers Demo](http://robotwebtools.org/demos/im.html).

**Details**

 Console from http://robotwebtools.org/demos/im.html:

<img width="597" alt="screen shot 2017-11-17 at 7 13 38 pm" src="https://user-images.githubusercontent.com/5094178/32976485-8b5953ec-cbcb-11e7-855e-1d93500d04ab.png">

Response from http://cdn.robotwebtools.org/threejs/current/three.min.js:

<img width="772" alt="screen shot 2017-11-17 at 7 13 56 pm" src="https://user-images.githubusercontent.com/5094178/32976486-9092deb4-cbcb-11e7-9150-87022709123e.png">

**Comment by hoangthien94** [comment]
I met the same issue when trying the [roslibjs tutorial](http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality).
I can solve it temporarily by downloading the requested files, in my case [roslib.js](https://github.com/RobotWebTools/roslibjs/tree/develop/build) and [eventemitter2.min.js](https://github.com/asyncly/EventEmitter2/tree/master/lib), place it locally, change the directory in the html file accordingly. After that I can run the example.
I don't know if the replacement files I use have the same content with the original files from cdn.robotwebtools.org or not (I haven't seen them before), so I can't say about their compatibility with other examples.
I think it's best if the necessary librarries are included in the repo.

**Comment by jihoonl** [comment]
CDN and all server are migrating to the new server at the moment. This issue will be resolved soon. I suggest to follow google mailing list

https://groups.google.com/d/msg/robot-web-tools/PlW1ECoL91Y/uI80cp3zDAAJ

**Comment by jihoonl** [comment]
I will keep it open until it gets fixed.

**Comment by jihoonl** [comment]
It is fixed now. Please refer this e-mail.

https://groups.google.com/d/msg/robot-web-tools/plGsZWwtNv8/1M3QCCV3AgAJ

**Comment by minshallj** [comment]
Thanks for that link :) Now to update everywhere cdn.robotwebtools.... is referenced! I issued a pull request (above) and requested edit permission for http://wiki.ros.org/action/login/roslibjs/Tutorials/BasicRosFunctionality but if anyone here already has edit permission feel free to `s/cdn.robotwebtools/static.robotwebtools/g` that page

**Comment by minshallj** [comment]
It looks like the entire robotwebtools.org website is down now :( not sure if there's a migration of where people are supposed to go now

**Comment by MatthijsBurgh** [comment]
How about https://robotwebtools.github.io/
