### ISSUE TITLE
node.js support

### ISSUE THREAD

**Issue by MKLNTF** [RobotWebTools/roslibjs#285]
Hello,

sorry for the beginner question, but I would like to know if it is possible to use this library with node.js?
There was a discussion about it in [Issue 53](https://github.com/RobotWebTools/roslibjs/issues/53) and [Issue 104](https://github.com/RobotWebTools/roslibjs/issues/104). Is it supported since back then?

**Comment by T045T** [comment]
Yes, NodeJS is supported. Roslibjs is [on npm](https://www.npmjs.com/package/roslib).
You might also want to take a look at [examples/node_simple.js](https://github.com/RobotWebTools/roslibjs/blob/develop/examples/node_simple.js).
