### ISSUE TITLE
Chagning the CDN links in the docs

### ISSUE THREAD

**Issue by shelddin** [RobotWebTools/roslibjs#298]
Hello,
I was trying your web tools in the past few days and realized that the CDN links in all pages in ROS wiki is not correct 
I would recommend changing it 
now it : cdn.robotwebtools.org/..
suppose to be : static.robotwebtools.org/..

and thank you all for your effort to provide such tools for the open source community

**Comment by helpceo** [comment]
npm install

**Comment by MatthijsBurgh** [comment]
Fixed
