### ISSUE TITLE
Can't connect to rosbridge server

### ISSUE THREAD

**Issue by youngbo-shim** [RobotWebTools/roslibjs#312]
Hello, I'm using roslibjs from CDN. And I just try a example simple.html but I always get the result below figure. As i know, this example can publish and subscribe some msg. But I can't see any topic...

![disconnect1](https://user-images.githubusercontent.com/15377045/51098860-8582dc80-1810-11e9-8987-04d4cca56ded.png)

The picture below is from rosbridge_websocket.launch.

![disconnected](https://user-images.githubusercontent.com/15377045/51098842-65ebb400-1810-11e9-8f84-941095ded33d.png)

And I already check the websocket server is running on port 9090

![9090check](https://user-images.githubusercontent.com/15377045/51098952-05a94200-1811-11e9-948c-df1624aaf1ae.png)

Let me know if you know how to fix it.

Thanks

**Comment by mvollrath** [comment]
Works for me on develop vs. rosbridge 0.10.1.  I followed the instructions.

**Comment by ubuntuslave** [comment]
@mvollrath what version of ROS are you using? Mine is also disconnecting immediately.

**Comment by mvollrath** [comment]
I've just tested roslibjs 1.0.0 on both kinetic and melodic Docker images with rosbridge installed via apt.  I don't think they are releasing rosbridge to indigo anymore, so ymmv there.

**Comment by jihoonl** [comment]
Yeah. I decided not to release in indigo anymore due to the hard dependency management.

**Comment by youngbo-shim** [comment]
My version of ROS is kinetic and roslibjs is 1.0.0.

I solved the problem, but the problem was the tornado version. I already installed the latest version of 5.1 tornado, but replaced it with version 4.5 compatible with roslibjs.

If you have a problem like me, I suggest you change the tornado version.

@mvollrath, @ubuntuslave , @jihoonl  Thank you for your answer.
