### ISSUE TITLE
roslibjs not working in melodic

### ISSUE THREAD

**Issue by dheera** [RobotWebTools/roslibjs#330]
The latest version of roslibjs seems to not work in Melodic. The websocket connects fine, but getTopics(cb) doesn't call the callback. Is this issue known and is there a workaround?

**Comment by dheera** [comment]
Found the solution: Downgrade tornado to 4.5.3: `sudo pip install tornado==4.5.3`

**Comment by ericq** [comment]
the above Downgrade tornado works. Thanks. Really want to know how it has this kind of issue.

**Comment by Rayman** [comment]
The solution: don't install packages with pip. Try to only use the packages provided by `apt-get`. These have been tested (and are often a little older).

**Comment by mvollrath** [comment]
Soon rosbridge will ship with Autobahn web socket server instead of Tornado, which should suffer much less from API churn.  Otherwise, as Rayman says, if you mix pip packages with ROS packages you're asking for trouble.
