### ISSUE TITLE
Can this library be used with React Native?

### ISSUE THREAD

**Issue by senakvkc** [RobotWebTools/roslibjs#341]
Hey there,

I've seen this library being used with React, but I've never encountered someone using roslibjs with React Native. So my question is, can I use it in my React Native project? I'm so very new in developing applications with React Native, so I really hope this is not a very simple question. 

Thanks in advance

**Comment by Rayman** [comment]
According to [this page](https://facebook.github.io/react-native/docs/network#websocket-support) websockets are supported in react native, but I've never tried it. Let us know if it works :)

**Comment by senakvkc** [comment]
Hey again, thanks for the info. Apparently, I can use it and works pretty much like how I wish it to. Thanks for the guidance :)
