### ISSUE TITLE
Subscribing and Publishing to ROsTopics isn't working

### ISSUE THREAD

**Issue by caelinsutch** [RobotWebTools/roslibjs#346]
I'm on ROS Melodic. I installed ros-melodic-desktop-full. I'm setting up a simple subscriber:
```
        const listener = new ROSLIB.Topic({
            ros: this.ros,
            name: '/test',
            messageType: 'std_msgs/UInt8',
        });
        listener.subscribe(msg => {console.log(msg)})
```

ros is already delcared and is connected (`this.ros.on('connection')` callback is being ran) but I can't seem to subscribe or publish. Any help is welcome!

**Comment by luyao514** [comment]
i met the same question.how do you solve it?

**Comment by MatthijsBurgh** [comment]
@luyao514 Please open a new issue, with more context.
