### ISSUE TITLE
Is there a non-nodejs TypeScript version available?

### ISSUE THREAD

**Issue by Aduen** [RobotWebTools/roslibjs#366]
I would like to use Roslibjs with TypeScript at client-side therefor I don't use Node.js NPM or any other server-sided runtimes.

Is there a ES6 compatible version with typing available perhaps? Or even better pure TS.. :)

Cheers!

**Comment by jorgenfb** [comment]
Hi! We use types from https://www.npmjs.com/package/@types/roslib for our frontend development.
