### ISSUE TITLE
How to subscribe a ros topic which user defined self?

### ISSUE THREAD

**Issue by herogan2017** [RobotWebTools/roslibjs#372]
var listener = new ROSLIB.Topic({
    ros : ros,
    name : '/slam/apa_location',
    messageType : 'msgs/apa_location'
  });

I hava a messageType defined by myself, not standard type. 
How to suscribe it using roslibjs?

thanks.

**Comment by Rayman** [comment]
The same way as subscribing to any other message.

**Comment by herogan2017** [comment]
> The same way as subscribing to any other message.

Thank you. I solve it.

**Comment by Surtr07** [comment]
Can you explain how to do it exactly? I want to use simple.html to listen a topic which msg defined by me.

**Comment by MatthijsBurgh** [comment]
I think the simple example is very straightforward. Change the `messageType` value to your message name. And change the object you provide to `ROSLIB.Message`.

**Comment by Surtr07** [comment]
> I think the simple example is very straightforward. Change the `messageType` value to your message name. And change the object you provide to `ROSLIB.Message`.

What do you mean change the  'ROSLIB.Message'?Isn`t the 'ROSLIB.Message' the content for publish a topic?

  var twist = new ROSLIB.Message({
    linear : {
      x : 0.1,
      y : 0.2,
      z : 0.3
    },
    angular : {
      x : -0.1,
      y : -0.2,
      z : -0.3
    }
  });

  cmdVel.publish(twist);

  var listener = new ROSLIB.Topic({
    ros : ros,
    name : '/obstacles_filter',
    messageType : 'common_msgs/DetectedObjectArray'
  });


  listener.subscribe(function(message) {
    console.log('Received message on ' + listener.name + ': ' + message.data);

Anything else should I change?

**Comment by MatthijsBurgh** [comment]
Sorry, Indeed you need to define a new message for publishing. For subscribing, the message is provided by `ROSLIB`, so the message has the correct structure.

**Comment by Surtr07** [comment]
> 

do you mean I can`t use a listener to show a topic which msg defined by myself? or how can I add a customized msg in ROSLIB?

**Comment by MatthijsBurgh** [comment]
ROSLIB, will do this for you. No need to register this custom msg.
