### ISSUE TITLE
Subscribe to any type

### ISSUE THREAD

**Issue by mirkow** [RobotWebTools/roslibjs#376]
Hi,

I would like to subscribe to a topic without knowing its type. And then use reflection to display the data. Is this possible with roslibjs?
If not, is there a way to first query the type of the topic and the use this to subscribe to that topic?

Thanks
Mirko

**Comment by jorgenfb** [comment]
Hi! I'm assuming you are running `rosbridge_suite` as your backend. `rosbridge_suite` includes `rosapi` to do its work. `rosapi` provides a lot of useful services that would probably suite your needs, including:

`/rosapi/topic_type` to lookup the type for a given topic
`/rosapi/topics` get all topics and their type

You can find all of them with `rosservice list | grep rosapi`

**Comment by MatthijsBurgh** [comment]
Solution provided
