### ISSUE TITLE
For loop taking lots of time on big images and blocks the interface

### ISSUE THREAD

**Issue by mizdan** [RobotWebTools/roslibjs#378]
For loop taking lots of time on big images and blocks the interface especially on mobile/tablet
Can a web worker be used for this process?

https://github.com/RobotWebTools/roslibjs/blob/6c17327cae14ca0c76ca5f71de5661279207219c/src/util/shim/decompressPng.js#L46

**Comment by Rayman** [comment]
roslibjs has 3 different methods for compressing messages:
- bson
- cbor
- png

You should be able to switch between them, they each have different cpu/space tradeoff.
