### ISSUE TITLE
Swift/iOS port?

### ISSUE THREAD

**Issue by ChrisPaliqaw** [RobotWebTools/roslibjs#380]
I posted this question on https://groups.google.com/g/robot-web-tools, but Jihoon suggested I open an issue here:

I'm looking to contribute my iOS skills to an open source project, and I'm wondering if an iOS port of roslibjs would be valuable. Being able to directly control ROS devices using mobile devices via websockets and perhaps later with BLE could open up interesting possibilities.

An example analogous use case is the Donkey Car mobile app:
http://docs.donkeycar.com/guide/mobile_app/

**Comment by trusktr** [comment]
We can already run roslibjs in a webview in Android or iOS. The webview would have the WebSocket API with which roslib communicates with.

Or, in other words, roslibjs is built for web, and the web runs on all devices, therefore roslibjs already can run on any device where a web browser or webview exists.

If you want to specifically port to another language, that could be a fun project. It would be more valuable for ROS in general, not necessarily valuable to roslibjs which is meant for web. F.e. you could make something like https://github.com/RobotSwiftTools/roslib.swift.

**Comment by christophomos** [comment]
Makes sense. At any rate, I'm working on a VR project instead.

**Comment by Rayman** [comment]
After some quick googling I found 2 ROS2 projects that might interest you:
- https://github.com/younata/rclSwift
- https://github.com/atyshka/ros2_swift
