### ISSUE TITLE
How to get Topic frequency and bandwidth?

### ISSUE THREAD

**Issue by VicenteQueiroz** [RobotWebTools/roslibjs#408]
This might be a dumb question but I've subscribed to a topic, I get the values and it works like a charm in my ReactJS application. But I only get the values. How to I get the publishing rate of the topic and how do I get the bandwidth?

**Comment by Rayman** [comment]
You'd have to calculate those yourself I think

**Comment by jaguardo** [comment]
Could try topic subscription (http://wiki.ros.org/Topics#Topic_statistics)
```
rosparam set enable_statistics true
```

then there is a new topic 
```
/statistics
```
 that might have some of what you want.

**Comment by MatthijsBurgh** [comment]
Use the suggestion above. This is not part of this library. As it is also not part of roscpp/rospy..
