### ISSUE TITLE
Feature Request: Add the ability to filter / limit data returned from "getTopicsAndRawTypes"

### ISSUE THREAD

**Issue by gkjohnson** [RobotWebTools/roslibjs#460]
Related to #351

The `getTopicsAndRawTypes` function affords the ability to return all the raw message type descriptions available which is extremely useful but this can result in a _huge_ bundle of data when there are a lot of topics which takes a while to send. It also returns redundant data if multiple topics share a single topic type -- in my case the amount of listed topic types (and therefore message definitions) is more than double what it needs to be and it takes ~13 seconds to receive the message through a localhost connection.

It would be nice if there were a way to filter the topics returned and / or cut down on redundant data included in these messages. Here are a couple API options that come to mind:

1. Add a topics array option to `getTopicsAndRawTypes` which limits the topics returned to the ones in the list.
2. Add a function like `getRawType` or `getRawMessageDescription` to return the just the "raw message description" for a single topic name (similar to `getTopicType` for topic names) so the app can request only the data it needs.

I'm leaning towards options 2 personally but I defer to the maintainers preference. I'm not an expert in ROSBridge or ROSLibjs but I can try to make PR if anyone can give me some guidance.

Thanks!

**Comment by MatthijsBurgh** [comment]
This library is not really actively developed. Mostly maintained. So If you want new features in this library, please develop these yourself and open a PR.

Though your request is mostly focused on reducing the data that is send. As the data is send by the `rosapi` node, you should open an issue/PR in that repo. `roslibjs` is only receiving, so when the data is received, the damage is already done.
