### ISSUE TITLE
Lag when subscribing to custom messages

### ISSUE THREAD

**Issue by RalphCodesTheInternet** [RobotWebTools/roslibjs#477]
Lag when subscribing to a custom Image message

- Version: 1.1.0 
- Platform: Ubuntu 20.04

Simply create your own custom message like this 
`
int32 width
int32 height
uint8[] data
`
Then use roslibjs to subscribe to the message and view it at normal FPS. 
Thereafter subscribe to a normal sensor_msgs/Image message and then view it at normal FPS.

The custom rosmessage has extreme lag, whereas the normal one does not have any. 

No compression on any of the two topics were used.

This happens with other custom messages as well

**Comment by MatthijsBurgh** [comment]
There is no code related to sensor_msgs in this repo, no optimizations etc. So the performance difference can't be caused by roslibjs.

So check the way you publish and first compare the frequency, bandwidth, etc. for the two different messages by other ros tools.
