### ISSUE TITLE
Fail to publish on iOS

### ISSUE THREAD

**Issue by chia-labradorsystems** [RobotWebTools/roslibjs#498]
**Description**
The exact same html works on PC / android.
On iOS devices, everything else is working as well, however, ROSLIB.Topic.publish doesn't work.
no error message as well. 

- Library Version: 1.0.1
- ROS Version: kinetic
- Platform / OS: Ubuntu 16.04 / iOS 15.0.2

**Comment by MatthijsBurgh** [comment]
I really have no clue. Our support doesn't go that far. I am sorry, but you will need to figure this out on your own.
