### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MatthijsBurgh** [RobotWebTools/roslibjs#500]
I am planning to release a new version.

I got some release instruction from @jihoonl, https://github.com/RobotWebTools/roslibjs/blob/release_process_document/RELEASE.md

Are there any issues that people want to have fixed before a new release. Please comment. I am aiming for a new release in the first week of January.

I don't think we have any breaking changes, so it will be a minor version bump. (https://github.com/RobotWebTools/roslibjs/compare/1.1.0...develop)

**Comment by MatthijsBurgh** [comment]
@RobotWebTools/roslibjs-maintainers @Rayman Please let me know what issues need to be fixed before a new release. Or when you have any comments on the release procedure.

**Comment by Rayman** [comment]
Due to the huge amount of "bump" commits I can't easiliy review what has changed...

**Comment by MatthijsBurgh** [comment]
I think if you check the changes per file, you get a good overview of the changes.

**Comment by jihoonl** [comment]
I think it would be better to deprecate CDN and keep only NPM versions. The CDN maintainer has been away for quite a long time.

**Comment by jorgenfb** [comment]
It would be great if #489 could be included. It prevents a leak in TFClient and should be fairly easy to include.

**Comment by MatthijsBurgh** [comment]
`1.2.0` has been released
