### ISSUE TITLE
Port roslibjs to work in Node.js

### ISSUE THREAD

**Issue by tlau** [RobotWebTools/roslibjs#53]
Having roslibjs running on top of Node.js would enable casual robot builders to quickly develop robot software using JavaScript.

The current version of roslibjs has some dependencies that assume you're running in a browser environment.

I've made some small tweaks to it that enable it to run inside of Node.js, but I wanted to get the community's advice on what to do with these changes and whether it would make sense to try to merge them with the main codebase.

There were two main issues I had to address:
- Using the EventEmitter built into Node.js rather than the external EventEmitter2
- Bring in a 3rd party library for WebSocket client functionality, which Node.js does not have

My changes are visible in my [fork of roslibjs](https://github.com/tlau/roslibjs) if you'd like to take a look at them. This version is currently working and tested in Node.js on my system, but I would love to get feedback. In particular I used some Meteor-specific code (because my system is built on Meteor) but it should be possible to remove that if  the code would be of general interest to the community.

**Comment by Snake-Sanders** [comment]
May I ask something regarding nodejs?

I am using the latest version of roslibjs.js and when I try to run a basic example from node.js the library complains about WebSocket not being defined.

I add the include like so...

`var WebSocket = require("ws");`

but then it starts asking me about the browser object "window"

````
roslib.js:4593
var Image = Canvas.Image || window.Image;
                            ^

ReferenceError: window is not defined
    at Object.45.canvas (/Users/Snake/src/node/roslib.js:4593:29)
    at o (/Users/Snake/src/node/roslib.js:2:265)
    at /Users/Snake/src/node/roslib.js:2:316
    at Object.19.../util/cborTypedArrayTags (/Users/Snake/src/node/roslib.js:3037:21)
    at o (/Users/Snake/src/node/roslib.js:2:265)
    at /Users/Snake/src/node/roslib.js:2:316
    at Object.15.../util/workerSocket (/Users/Snake/src/node/roslib.js:2241:21)
    at o (/Users/Snake/src/node/roslib.js:2:265)
    at /Users/Snake/src/node/roslib.js:2:316
    at Object.21.../mixin (/Users/Snake/src/node/roslib.js:3362:10)
```

How can I run it on nodejs without having to change the library roslib.js?
Thank you in advance
