### ISSUE TITLE
On close or error is slow

### ISSUE THREAD

**Issue by madsh93** [RobotWebTools/roslibjs#543]
Hi

I’m using the Ros.on(“error”) and Ros.on(“close”) to set a global State in my vue app whether it’s online or offline.

However, when testing (disabling Wi-Fi) it often takes a long time 1-3 minutes before the function is executed. Why is that? And what can I do to make it faster?

With Ros.on(“connected”) it seems to be instant.

**Comment by MatthijsBurgh** [comment]
These events are connected to the events of the socket. So it depends on the chosen socket implementation. But this behaviour can't be changed in this library.
