### ISSUE TITLE
ROSlib not receiving all Logs from /rosout_agg

### ISSUE THREAD

**Issue by owuraku-zenas** [RobotWebTools/roslibjs#559]
**Description**
I'm using ROSlibjs to subscribe to /rosout_agg and I'm not receiving all the logs. Only level 2 and error logs come through but ```rostopic echo /rosout_agg``` echos all the logs. Is this issue from end?

- Library Version: roslib: ^1.1.0
- ROS Version: Noetic
- Platform / OS: Ubuntu 20.04 LTS

**Steps To Reproduce**

```javascript
var rosout_agg = new ROSLIB.Topic({
                ros: ros,
                name: "/rosout_agg",
                messageType: "rosgraph_msgs/Log"
})
rosout_agg.subscribe((message) => {
            let today = new Date();
            let date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
            let time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
            let dateTime = date + ' ' + time;
            console.log(dateTime)
            console.log("message", message);
            setLogs([...logs, { date: dateTime, data: message }])
            localStorage.setItem('logs', JSON.stringify(logs))
})
```
**Expected Behavior**

**Actual Behavior**

**Comment by MatthijsBurgh** [comment]
With level 2, you mean info level?

You are just using a generic topic. So ROSLIB is not doing any magic there. Try to subscribe to a custom topic on which you just publish manually.

If that fails to work, try the syntax used in the test example, https://github.com/RobotWebTools/roslibjs/blob/112f8dc07592686161a21b777dca5432678a73be/test/examples/pubsub.example.js#L31-L37
