### ISSUE TITLE
Working demos 404 link

### ISSUE THREAD

**Issue by supertick** [RobotWebTools/roslibjs#584]
Documentation link on README.md 
"working demos" - not working

link - http://robotwebtools.org/demos.html

![image](https://user-images.githubusercontent.com/1266144/209702144-cec7792a-0f5e-4681-96c1-fc50cf33fb78.png)

**Comment by MatthijsBurgh** [comment]
Demo's are not hosted anymore.

**Comment by supertick** [comment]
Then you might consider updating the README.md

**Comment by MatthijsBurgh** [comment]
@supertick Done in #585
