### ISSUE TITLE
configurable goal_id in roslib Goal 

### ISSUE THREAD

**Issue by guptaashwanee** [RobotWebTools/roslibjs#591]
Roslib.Goal() should also accept goal_id along with options, this will help to identify different types of goal and another property.

**Comment by MatthijsBurgh** [comment]
I am not sure yet, you can still access the goalID after creating the goal. So why do you need to set it manually? This allows for duplicate goalIDs, which is a very significant issue.

So please make your case and refer to the original python/cpp implementation.

**Comment by MatthijsBurgh** [comment]
No response, closing this.
