### ISSUE TITLE
What to do with socket.io?

### ISSUE THREAD

**Issue by MatthijsBurgh** [RobotWebTools/roslibjs#648]
We allow usage of `socket.io` as transport layer. Though it is not included in the library. So the user should provide it him/herself.

Though it isn't tested. So I don't know whether it works.

We should clean up this situation.

Related:
https://github.com/RobotWebTools/roslibjs/pull/429

**Comment by EzraBrooks** [comment]
My ongoing adventures with typescript type checking seem to imply that this feature does not actually work, because the code as written doesn't compile due to a function signature mismatch

**Comment by MatthijsBurgh** [comment]
So I suggest to drop it.
