### ISSUE TITLE
Roslibjs crashes on Infinity value

### ISSUE THREAD

**Issue by tlau** [RobotWebTools/roslibjs#68]
In ROS floating-point numbers are allowed to have an "Infinity" value. This gets serialized by rosbridge as follows (e.g. for a type std_msgs/Float32 ROS message):

{"data": Infinity}

This string is invalid JavaScript and causes JSON.parse() to barf (https://github.com/RobotWebTools/roslibjs/blob/devel/src/core/Ros.js#L125). 

Ideally this would be fixed on both sides and enable transmission of Infinity values from ROS to the browser. Until then, it would be nice to put a guard around the JSON.parse on the roslibjs side so that at least garbage inputs don't cause an uncaught exception.

It looks like Infinity and NaN values are not allowable in JSON: http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

Any thoughts on how to handle this?

**Comment by T045T** [comment]
Should be fine since https://github.com/RobotWebTools/rosbridge_suite/pull/116 and https://github.com/RobotWebTools/rosbridge_suite/pull/120 have been merged.
