### ISSUE TITLE
Node.js: ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [RobotWebTools/roslibjs#756]
**Description**

The shim logic for deciding which WebSocket library to load runs _after_ some code that tries to use the browser-specific `WebSocket` global:
https://github.com/RobotWebTools/roslibjs/blob/39158ec5fdb8ad540461ad92f2447ecdaef4757c/src/core/Ros.js#L64

This, in Node.js, then results in the error in the title -- `ReferenceError: WebSocket is not defined`.

- Library Version: https://github.com/RobotWebTools/roslibjs/commit/7657e2bfebc93faa860e121ad10f13d70c517bd3
- ROS Version: Iron
- Platform / OS: Linux

**Steps To Reproduce**
* Create a connection
* Try to connect without ROS ready/running yet, so the first attempt fails and `this.socket` is set but it's not connected
* Try to reconnect after ROS is ready
* :boom:

**Expected Behavior**
It shouldn't crash

**Actual Behavior**
It crashes

**Possible Fix**
Since the value of this constant appears to be set by the WhatWG spec (https://websockets.spec.whatwg.org/#dom-websocket-closed), I think it can just be replaced with `... === 3` and an appropriate comment.

Alternately, the nesting order of the different `if` conditions could be changed so it checks `... === ws.WebSocket.CLOSED` on the Node.js branch.

**Comment by ghost** [comment]
We have also seen this bug. I My first reaction would be @mgabeler-lee-6rs first solution to keep the logic flow the same but either will do.
