### ISSUE TITLE
Gruntfile.js cannot be found.

### ISSUE THREAD

**Issue by kosei1515** [RobotWebTools/roslibjs#806]
**Gruntfile.js cannot be found.**
Since Gruntfile is not found on current `develop` branch, I cannot build roslibjs as described in [CONTRIBUTING.md](CONTRIBUTING.md). 
Should I use Gruntfile on other branches such as `ros2`?

**Comment by kosei1515** [comment]
Currently, I use [`v 1.4.1`](https://github.com/RobotWebTools/roslibjs/releases/tag/1.4.1). It works.

**Comment by MatthijsBurgh** [comment]
Just use npm, `npm run build`
